SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Coin Race"

PLAYER_SPEED = 4

LEVEL_TIME_SECONDS = 60

SCORES_FILE = "scores.txt"

TILE = 50
COLS = SCREEN_WIDTH // TILE
ROWS = SCREEN_HEIGHT // TILE
MAP_W = COLS * TILE
MAP_H = ROWS * TILE
